# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 990b6e7130591c66aeac40cc3014933c87990676905c899463b4b274531b1e3d9f9cb83c99c9b24648efdcd64cb02b2c153ebe9f5add8af0c4310badced25aae

test:
  secret_key_base: addf519d5949df2209c9109c150245f6b569f5b11ed4d53d4e18d24b5e408e64f6d8732eec075fe597fd59e373d139ecf2bf5d4fc59a6940a7f82b9ff7b767e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
